version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
    command: sh -c 'cd app && yarn start'
    ports:
      - '3000:3000'
    tty: true

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/app:/app
    ports:
      - '8000:80'
    tty: true
